name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:   

      - name: print Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version
          
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: google-chrome --version
      - run: chromedriver --version
      - run: npm test
